In [66]:
import pandas as pd

table = pd.read_csv("telecom_users.csv")



#exluir a coluna de uma tabela

# table.drop("nome-da-coluna ou linha", "axis -> é eixo da linha ou da coluna ") 
    # axis = 0 -> linha
    #axis = 1 -> coluna

    
table = table.drop("Unnamed: 0", axis=1) # deletar a tabela inútil

##para deletar mais de uma coluna, colocar os nomes entre colchetes


#comando para exibir informação da table -> print(table.info())

# object é quando está reconhecendo os valores de uma tabela como texto
# int quando reconhece coluna com valores inteiro
# float quanto está reconhecendo uma coluna com valores decimais

table["TotalGasto"] = pd.to_numeric(table["TotalGasto"], errors="coerce")

# coerce -> tratamento de erros que transforma um valor de erro em valor vazio

#dropna -> drop inteligente

table = table.dropna(how="all", axis=1) #all exlui table que tem todos os valores vazios

table = table.dropna(how="any", axis=0) # any -> exlui a coluna que tem pelo menos um valor vazio

###print(table)

###########

# 3) Análise Inicial

print(table["Churn"].value_counts(normalize="True"))

# 4) Análise Detalhada

print(table)

Nao    0.734349
Sim    0.265651
Name: Churn, dtype: float64
       IDCliente     Genero  Aposentado Casado Dependentes  MesesComoCliente  \
0     7010-BRBUU  Masculino           0    Sim         Sim                72
1     9688-YGXVR   Feminino           0    Nao         Nao                44
2     9286-DOJGF   Feminino           1    Sim         Nao                38
3     6994-KERXL  Masculino           0    Nao         Nao                 4
4     2181-UAESM  Masculino           0    Nao         Nao                 2
...          ...        ...         ...    ...         ...               ...
5981  0684-AOSIH  Masculino           0    Sim         Nao                 1
5982  5982-PSMKW   Feminino           0    Sim         Sim                23
5983  8044-BGWPI  Masculino           0    Sim         Sim                12
5984  7450-NWRTR  Masculino           1    Nao         Nao                12
5985  4795-UXVCJ  Masculino           0    Nao         Nao                26

     ServicoTelefone MultiplasLinhas ServicoInternet ServicoSegurancaOnline  \
0                Sim             Sim             Nao            SemInternet
1                Sim             Nao           Fibra                    Nao
2                Sim             Sim           Fibra                    Nao
3                Sim             Nao             DSL                    Nao
4                Sim             Nao             DSL                    Sim
...              ...             ...             ...                    ...
5981             Sim             Nao           Fibra                    Sim
5982             Sim             Sim             DSL                    Sim
5983             Sim             Nao             Nao            SemInternet
5984             Sim             Sim           Fibra                    Nao
5985             Sim             Nao             Nao            SemInternet

      ... ProtecaoEquipamento ServicoSuporteTecnico ServicoStreamingTV  \
0     ...         SemInternet           SemInternet        SemInternet
1     ...                 Sim                   Nao                Sim
2     ...                 Nao                   Nao                Nao
3     ...                 Nao                   Nao                Nao
4     ...                 Sim                   Nao                Nao
...   ...                 ...                   ...                ...
5981  ...                 Nao                   Nao                Sim
5982  ...                 Sim                   Sim                Sim
5983  ...         SemInternet           SemInternet        SemInternet
5984  ...                 Sim                   Nao                Sim
5985  ...         SemInternet           SemInternet        SemInternet

     ServicoFilmes TipoContrato FaturaDigital    FormaPagamento ValorMensal  \
0      SemInternet       2 anos           Nao     CartaoCredito       24.10
1              Nao       Mensal           Sim     CartaoCredito       88.15
2              Nao       Mensal           Sim  DebitoAutomatico       74.95
3              Sim       Mensal           Sim  BoletoEletronico       55.90
4              Nao       Mensal           Nao  BoletoEletronico       53.45
...            ...          ...           ...               ...         ...
5981           Sim       Mensal           Sim  BoletoEletronico       95.00
5982           Sim       2 anos           Sim     CartaoCredito       91.10
5983   SemInternet       Mensal           Sim  BoletoEletronico       21.15
5984           Sim       Mensal           Sim  BoletoEletronico       99.45
5985   SemInternet        Anual           Nao     CartaoCredito       19.80

      TotalGasto  Churn
0        1734.65    Nao
1        3973.20    Nao
2        2869.85    Sim
3         238.50    Nao
4         119.50    Nao
...          ...    ...
5981       95.00    Sim
5982     2198.30    Nao
5983      306.05    Nao
5984     1200.15    Sim
5985      457.30    Nao

[5974 rows x 21 columns]

In [83]:
import plotly.express as px

#sempre que for criar um gráfico, usamos duas linhas de codigo

#1)linha para criar o gráfico
#2) exibir o gráfico

for coluna in table.columns:

    coluna = "MesesComoCliente"
    grafico = px.histogram(table, x=coluna, color="Churn")
    grafico.show()

TypeError: pie() got an unexpected keyword argument 'x'